Fix exception when rendering /demo service (fix regression of PR #572)
A side effect of PR #572 was the following exception when rendering /demo
```
  File "/home/even/spatialys/cnes/2022/mapproxy/mapproxy/util/ext/tempita/__init__.py", line 288, in _eval
    value = eval(code, self.default_namespace, ns)
  File "<string>", line 1, in <module>
  File "/home/even/spatialys/cnes/2022/mapproxy/mapproxy/service/demo.py", line 161, in layer_srs
    sorted_uncached_srs = sorted(uncached_srs, key=lambda srs: get_epsg_num(srs))
TypeError: '<' not supported between instances of 'NoneType' and 'int' at line 59 column 39 in file /home/even/spatialys/cnes/2022/mapproxy/mapproxy/service/templates/demo/demo.html
```

This PR corrects this and adds a minimal test/system/test_demo.py