Support caching of dimension layers with WMS and WMTS
Add support for time ranges and miscelaneous

Fix default behavior in WMS demo

Fix error en exception handling

go back to last version in master for forward_req_params

Using FileCache instead of DummyCache for dimensions

Move dimension handling to the FileCache level to be reused across cache structures

Fixing wmts test, disable storage when it is true

adding dimensions to wms service

Fixing TypeError: is_cached() got an unexpected keyword argument 'dimensions'

delete prints

Adding ISO 8601 Time intervals

Adding ISO8601 Error